### ISSUE TITLE
markdoc build deletes .htaccess file

### ISSUE THREAD

**Issue by oliversalzburg** [zacharyvoase/markdoc#15]
I hope I'm not misinterpreting here, but it seemed to me like invoking `markdoc build` would remove potentially created `.htaccess` files in the `.html` output directory.

This was a bit confusing to me when I read [this tip](http://markdoc.org/tips/apache).

All went well in the end, I just configured it directly in the profile for the virtual host :)

**Comment by timmerk** [comment]
oliversalzburg: you need to put the .htaccess file into your wiki's static folder, and then it will work. I don't think this is a bug.

**Comment by oliversalzburg** [comment]
Good point. I guess I hadn't thought about it at that point :) Thanks
