### ISSUE TITLE
An "edit" link on markdoc pages?

### ISSUE THREAD

**Issue by dylanmc** [zacharyvoase/markdoc#28]
A wiki isn't really a wiki unless the rendered pages (can) have an edit link. A markdown-format wiki is exactly what I'm after, but I'd like to be able to add / edit content via my web browser, and not just the command line. Or is this there, and I just missed it (after reading all the documentation)?

**Comment by cawel** [comment]
I had the exact same reaction. And I also read most of the documentation. It would seem natural to me that a wiki would have an "edit" link on all its pages (maybe after some authentication/authorization). Otherwise it's just a (cool) markdown-formatted file viewer.

**Comment by zacharyvoase** [comment]
Markdoc is intended as a wiki for programmers who are confident and competent at the command line. To introduce editing features would dramatically increase the complexity of the project and introduce assumptions about version control systems which I deliberately didn’t add.

If you want a Markdown wiki with in-browser editing, I strongly recommend [Gollum](https://github.com/gollum/gollum).

**Comment by cawel** [comment]
Thank you for both your reply and your pertinent recommendation.
